<?php
/**
 * @file
 * Code for the Stanford Guides Search feature.
 */

include_once 'stanford_guides_search.features.inc';
include_once 'includes/stanford_guides_search.form.inc';
  
/**
 * Implements hook_menu()..
 */
function stanford_guides_search_menu() {
  $items['guides-search'] = array(
    'title' => 'Guidelines & Policies',
    'page callback' => 'stanford_guides_search_results',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
* Implements hook_block_info().
*/
function stanford_guides_search_block_info() {
  global $user;
  $blocks = array();
  $blocks['guides_search'] = array(
    'info' => t('Guides Search'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function stanford_guides_search_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'guides_search':
      $block['subject'] = '';
      $block['content'] = _stanford_guides_search_content();
      break;
  }
  return $block;
}

/**
* Custom return function for guides_search block.
*/
function _stanford_guides_search_content() {
  $output = drupal_get_form('stanford_guides_search_input_form');
  return $output;
}


function stanford_guides_search_results() {
  $topic_ids = array_keys(taxonomy_allowed_values(field_info_field('field_s_guides_topic')));
  $topic_ids = array('All' => 'All') + $topic_ids;
  if (isset($_POST['keyword'])) {
    $arg1 = $_POST['keyword'];
    variable_set('stanford_guides_keyword', $arg1);
  } else {
    $arg1 = variable_get('stanford_guides_keyword', '');
  }
  if (isset($_POST['topic'])) {
    $arg2 = $_POST['topic'];
    variable_set('stanford_guides_topic', $arg2);
  } else {
    //$arg2 = variable_get('stanford_guides_topic', array_shift($topic_ids));
    $arg2 = variable_get('stanford_guides_topic', $topic_ids);
  }
  $view = views_get_view('guides_search');
  $view->exposed_input['combine'] = $arg1;
  $view->exposed_input['field_s_guides_topic_tid'] = $arg2;
  $view->set_display('page_1');
  $view->is_cacheable = FALSE;
  $view->execute();
  $view = $view->preview();
  return $view;
}

/**
* Implements hook_form_alter().
*/
function stanford_guides_search_form_alter(&$form, &$form_state, $form_id) {
  if ($_GET['q'] == 'guides' && $form_id == 'stanford_guides_search_input_form') {
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'stanford_guides') . '/modules/stanford_guides_search/js/stanford_guides_search.js',
    );
  }
}

/**
* Implements hook_user_logout().
*/
function stanford_guides_search_user_logout($account) {
  //Reset variables to default when the user logs out.
  variable_set('stanford_guides_keyword', '');
  variable_set('stanford_guides_topic', 'All');
}
